name: Artifacts
on: [pull_request]
jobs:
  test:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0-dev.3027+0e26c6149
      - run: |
          zig build test -Dfetch -Dci_target=${{matrix.os}}-${{matrix.arch}}
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: zigup ${{ matrix.os }}
          path: zig-out/bin/*
